// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1RPgRYcfiYjvl5fUZJok_ibl3JY6LLZo',
    appId: '1:67083259260:web:197834152c8c36798a68f9',
    messagingSenderId: '67083259260',
    projectId: 'ddhprr-fods',
    authDomain: 'ddhprr-fods.firebaseapp.com',
    storageBucket: 'ddhprr-fods.appspot.com',
    measurementId: 'G-9CCB9VKNEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByjnZQvSRstT9GITY69FeABYTD72N3cDs',
    appId: '1:67083259260:android:5694986a7baefccd8a68f9',
    messagingSenderId: '67083259260',
    projectId: 'ddhprr-fods',
    storageBucket: 'ddhprr-fods.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvjEt3iFXP0ss7y2XQFmoIjgLwf-VoBFI',
    appId: '1:67083259260:ios:daeb388d748ed1a38a68f9',
    messagingSenderId: '67083259260',
    projectId: 'ddhprr-fods',
    storageBucket: 'ddhprr-fods.appspot.com',
    iosClientId: '67083259260-p0ulrkme4gtpt4be60kqk87jl76kateh.apps.googleusercontent.com',
    iosBundleId: 'com.fods.customerapp',
  );
}
